server:
  port: 8081

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cravedash
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
